### ISSUE TITLE
form commit data can not collection

### ISSUE THREAD

**Issue by zhouyu94** [akamai/boomerang#259]
When I used this plugin, I found that the request submitted by the form form was not collected. Can I say why I didn't collect it or why I didn't monitor the form submission?

**Comment by zhouyu94** [comment]
i found BOOMR add the `submit` listener, and when submit , the BOOMR fire `submit` event, but i dont see any form submit beacon, what should i do, config anything?

**Comment by bluesmoon** [comment]
boomerang does not fire a beacon on form submit. It only captures the timestamp and saves it in a cookie.

**Comment by zhouyu94** [comment]
Are there any plans to add this part of the function in the future?

**Comment by bluesmoon** [comment]
boomerang sends beacons when the page load is complete, not when the user initiates an action. There is a separate beacon sent when the page unloads, but that has to be very small otherwise it will not reach the server.  In any event, sending the full contents of a form submission doesn't make sense as that is already being sent to your server.
