### ISSUE TITLE
CICD Setup for Akamai Boomerang Repo

### ISSUE THREAD

**Issue by sukratkashyap** [akamai/boomerang#276]
After looking at this comment https://github.com/akamai/boomerang/pull/274#issuecomment-533368299

I feel it will be better if we place a CICD setup for this Repository. I will be more than happy to create PR with the configuration. But I would like to know which CI would you like me to create for or rather which CI agent you can enable for this repo?

Travis, Circle, Azure Pipelines?

**Comment by nicjansma** [comment]
@sukratkashyap we're definitely open to getting a CI setup for Boomerang.  One of the challenges is our current build/test pass takes a good 50+ minutes to run and requires a headless Chrome.  I've used Travis in the past, but they have a 30-minute time limit on builds.

We could (and should) just do the build / lint steps easily.  Feel free to open a PR if you're inclined, otherwise we'll give it a stab sometime soon.

**Comment by nicjansma** [comment]
Great work here!
