### ISSUE TITLE
Sending XHR/fetch errors without also sending successes

### ISSUE THREAD

**Issue by qoobic** [akamai/boomerang#278]
Hello everyone,

Firstly, thanks for providing a great utility!

I am already using Boomerang to record page time but I am looking to extend my usage to capture errors encountered on the browser, ie runtime, console, XHR and fetch errors via the Errors plugin.

My issue is I do not want to record details of **successful** XHR/fetch requests, as they will be duplicates in my logs and create a lot of noise. Currently requests returning 2XX HTTP status are being logged. My configuration is:

`BOOMR.init({
    beacon_url: "http://www.mocky.io/v2/5d9dade83200008407329830", // sample URL returns 200 HTTP status
    UserTiming: {
        enabled: true
    },
    History: {
        enabled: true,
        auto: true
    },
    Errors: {
        sendAfterOnload: true,
        sendInterval: 5000,
        monitorConsole: true
    },
    instrument_xhr: true,
    AutoXHR: {
        monitorFetch: true
    }
});`

Can someone please advise how I need to update my code to suppress successful XHR/fetch from being reported, as it slightly unclear to me if this is possible via configuration?

I am not sure if this is an **issue** or rather more a question on how to use Boomerang but I could not find how to do this hence asking here in case it is not supported (in which case I would ask that it be supported as a new feature).

Thanks
Jay

**Comment by bluesmoon** [comment]
If you don't want to monitor XHRs, then disable the `AutoXHR` and `History` plugins. If you only want `Errors`, then that's the only plugin you need.

**Comment by qoobic** [comment]
Any further advice would be greatly appreciated. I am hopeful this is not a bug, just a case of configuring the framework correctly.

**Comment by ceckoslab** [comment]
Hello @qoobic,

I guess that you are looking fore XHRs with response codes 5xx.

If this is correct you may try to check the beacons you received for `http.errno`.

You also may try to slightly modify Boomerang in order to exclude successful XHRs beacons of being sent. This solution will work when the RT plugin is enabled. Please keep in mind that this will be your patched version of Boomerang.

In boomerang.js in function in function `real_sendBeacon` after the code `BOOMR.debug("Checking if we can send beacon");` add this:
```
if ('xhr' === impl.vars["http.initiator"] && impl.vars["http.errno"] === undefined) {
	return false;
}
```

When you have `impl.vars["http.errno"] !== undefined` this means that you will receive all possible errors including aborted XHRs or XHRs with timeouts.

If you want to get only XHRs with 5xx then change the condition to:
```
if ('xhr' === impl.vars["http.initiator"] && impl.vars["http.errno"] < 500) {
	return false;
}
```

**Comment by qoobic** [comment]
Thanks @ceckoslab this looks like it will work :-)

**Comment by ceckoslab** [comment]
Hey @qoobic 

Let us know if this worked for you :)

**Comment by qoobic** [comment]
Hi all,

The above code didn't seem to work - the 200 requests were indeed not sent but subsequent 4XX requests after a 200 didn't send either.

As an alternative, I made a change to the AutoXHR plugin as per the below patch. This seems to work fine, even in the case where multiple XHRs are fired off one after another (thus sending a single beacon with multiple errors).

Can someone please tell me if there is a good reason not to make the change this way?

```Index: plugins/auto-xhr.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- plugins/auto-xhr.js	(revision 63702293297a3e8af4fbc631a8e6e28d08348fff)
+++ plugins/auto-xhr.js	(date 1571825407998)
@@ -720,6 +720,17 @@
 				return;
 			}
 
+			// if ignoreSuccessfulResponses is true, ensure we don't fire a beacon for a successful XHR/fetch response
+			if (impl.ignoreSuccessfulResponses && ev.type === "xhr") {
+				// status is only populated for non-success ie status < 200 || status >= 400
+				if (typeof ev.resource.status === "undefined") {
+					debugLog("Excluding successful XHR from beacon");
+					BOOMR.fireEvent("xhr_ignore"); // a new event, in case it is required
+					this.pending_events[index] = undefined;
+					return;
+				}
+			}
+
 			if (BOOMR.utils.inArray(ev.type, BOOMR.constants.BEACON_TYPE_SPAS)) {
 				// save the last SPA location
 				self.lastSpaLocation = ev.resource.url;
@@ -2211,6 +2222,7 @@
 		fetchBodyUsedWait: FETCH_BODY_USED_WAIT_DEFAULT,
 		spaIdleTimeout: SPA_TIMEOUT,
 		xhrIdleTimeout: CLICK_XHR_TIMEOUT,
+		ignoreSuccessfulResponses: false,
 
 		/**
 		 * Filter function iterating over all available {@link FilterObject}s if
@@ -2417,7 +2429,7 @@
 			// gather config and config overrides
 			BOOMR.utils.pluginConfig(impl, config, "AutoXHR",
 			    ["spaBackEndResources", "alwaysSendXhr", "monitorFetch", "fetchBodyUsedWait",
-			    "spaIdleTimeout", "xhrIdleTimeout"]);
+			    "spaIdleTimeout", "xhrIdleTimeout", "ignoreSuccessfulResponses"]);
 
 			BOOMR.instrumentXHR = instrumentXHR;
 			BOOMR.uninstrumentXHR = uninstrumentXHR;```

**Comment by ceckoslab** [comment]
Hello @qoobic 

I do not see a problem in your code and if you like you could keep it. I am not sure if we will backport it to Boomerang library but you introduced some good ideas like firing event `xhr_ignore` and making possible to enable the feature by configuration `ignoreSuccessfulResponses`.

As alternative you could just change my proposal from:
```
if ('xhr' === impl.vars["http.initiator"] && impl.vars["http.errno"] < 500) {
	return false;
}
```

to:
```
if ('xhr' === impl.vars["http.initiator"] && impl.vars["http.errno"] < 400) {
	return false;
}
```

**Comment by nicjansma** [comment]
Hi @qoobic your solution seems straightforward, and I don't have any concerns about it working for you.  Let us know how it goes.

I would say that if we wanted to offer something similar in the official Boomerang repo, we could make it a little more generic.  i.e. an option called something like `xhrCompletionFilter` that is a function, which runs in the same `sendEvent()` function.  If the option is specified and running it returns `false`, the beacon would be dropped as you're doing above.

If you're interested in opening a PR for something like the above, feel free!  Otherwise, closing this out as it sounds like you have a solution.
