### ISSUE TITLE
Q: library size increase between 2012 and 2019 versions

### ISSUE THREAD

**Issue by aaarichter** [akamai/boomerang#279]
My company has been using the original boomerang from 2012 (version 0.9.3) for a long time. After updating to the 2019 version, I noticed that the Boomerang.js base library has increased 5x in size (2kb vs 10kb gzipped and minified), the important RT plugin 3x (1.52 vs 4.5kb) and e.g NavTimings also by 3x times.

<img width="1910" alt="Screen Shot 2019-10-20 at 6 12 13 PM" src="https://user-images.githubusercontent.com/2707029/67168033-7152a980-f365-11e9-9a0c-02b0ac5004f5.png">

Questions:
1. Is a more modular and configurable approach possible in order to reduce the size of the library, thus it's download, parse and evaluation time. 
2. Boomerang supports old browsers like IE8. What are the plans to drop support for legacy browsers?

**Comment by ceckoslab** [comment]
Hello @aaarichter 

I prefer to answer to your 2 questions once I gather more information but anyway I would like to bring some ideas.

RT and other plugins advanced a lot during last 7 years and as result Boomerang started collecting and reporting much more metrics.

I guess that for you is important to collect the metrics you really want to analyze. Probably you will find it interesting if some of the new introduced beacon params make sense for your analyses: https://developer.akamai.com/tools/boomerang/docs/BOOMR.plugins.RT.html

For reference you may take a look at this diff that shows what is new between 2012 and 2019: https://www.diffchecker.com/1LCjyj7g 

Regards!

**Comment by nicjansma** [comment]
It's important to us as well to keep down the size of Boomerang and its plugins, but it has also unfortunately grown from new features, bug fixes, browser APIs, etc.

You can read about some of the size reductions we've made over the past year in [this post](https://nicj.net/boomerang-performance-update/), but at the same time we've grown the library at about the same rate due to new features/etc.

The good news is with custom builds where you choose to include the plugins you want, you do have some control over the size.  However, you're correct the `RT` and `NavigationTiming` plugins have both grown a bit since 2012 :)

We're definitely open for idea on how to reduce library size further or make it more modular.  Please let us know what kind of thoughts you have.  PRs welcome!
