### ISSUE TITLE
TTI differences between browsers (very high on Firefox)

### ISSUE THREAD

**Issue by scottgifford** [akamai/boomerang#292]
For our site, we are using the Continuity plugin to calculate TTI, and we are seeing significant variation between browsers.  In particular, our p90 TTI for Chrome is about 8s, while for Firefox it is 13.6s.

I was wondering if other Boomerang users had similar experiences, and if there was consensus around what kinds of differences to expect between browsers?  Does anybody have tips on common configuration settings that could cause such a large difference?

Also I was wondering if anybody had tips on troubleshooting a problem like this, understanding what is going on for these slow Firefox users that is different from my own Firefox usage, which is closer to the Chrome TTI?

Finally, assuming this really is that much slower on Firefox, anybody have any Firefox-specific performance tuning tips?

Thanks for any thoughts!

**Comment by bluesmoon** [comment]
What's the sample size for the two browsers? It might be worth it to
calculate a margin of error or median absolute deviation for each and see
if there's overlap between the value ± error.

Browser differences could definitely contribute to this, but first make
sure you're looking at the data correctly.


Philip

**Comment by scottgifford** [comment]
Sample size is pretty large, about 140M (million) page view entries for Chrome, 24M for Firefox, another 35M or so for other browsers.

I'll need to do a little more data analysis to find the margin of error, but I would expect it to be pretty low with that much data.

**Comment by bluesmoon** [comment]
agreed, that's enough data to be confident in the numbers. Other things to check would be how the population at the 90th percentile is different for the 2 browsers. Are there other confounding factors at play?

**Comment by scottgifford** [comment]
I dug in for confounding factors, and even when controlling for OS and Version, user country, and internal vs. external traffic the results were comparable.  I also looked at robot traffic and non-Desktop traffic, but none of that was classified as Firefox.

Those are pretty much all the dimensions I have in my data, any others that seem useful to look at?

One thing I was particularly interested in here was whether other users see similar results.  If they do, probably I need to dig into Boomerang and the browser.  If they don't, probably I need to dig into our configuration and Web site.

**Comment by drelementzero** [comment]
Any update on this?

**Comment by nicjansma** [comment]
@scottgifford one factor that may be part of the difference is that Chrome is currently the only browser that supports Long Tasks, which is the most "accurate" signal we use for Time to Interactive calculations.

Some notes on how we calculate TTI for RUM in Boomerang is here:
https://akamai.github.io/boomerang/BOOMR.plugins.Continuity.html#toc10__anchor

```
After Visually Ready Timestamp, calculate Time to Interactive by finding the first period
of 500ms where all of the following are true:

* There were no Long Tasks
* The FPS was always above 20 (if available)
* Page Busy was less than 10% (if the above aren't available)
```

Long Tasks give us very precise information about main-thread usage (for tasks >50ms), while FPS calculations are more like second-hand information about how busy the main-thread is.  I would expect browsers that support Long Tasks to be generally more accurate with our calculation as a result.

Modern Chrome will use both Long Tasks (since it supports it) and FPS as signals, while Firefox will only use FPS.  All other things being equal (which they aren't), by Chrome having _more_ information available via Long Tasks, I might expect its TTI to be _slightly higher_, i.e. it might find more periods where there were Long Tasks that there was no FPS drop.  So seeing Firefox having a significantly larger TTI than Chrome here leads me to think there might actually be a browser reason why Firefox is slower.

There is a lot of debugging information that can be added to the beacon, if you have the [timeline](https://akamai.github.io/boomerang/BOOMR.plugins.Continuity.html#toc13__anchor) enabled, it'll log the FPS over each 100ms interval.  And if the Long Task debug information in `c.lt` and timeline `c.t.lt` will show when those happen.  Maybe you can narrow down to a particular page / device / geolocation and compare a few traces to see what's going on?

Do you see Page Load times with such dramatic differences too?

FWIW I looked at median TTI over two of my personal websites, and see Chrome with a generally smaller TTI:

## Site 1
Firefox TTI is 2x of Chrome TTI:
![image](https://user-images.githubusercontent.com/1004649/77942780-24ff8400-728a-11ea-839f-8369e3ae47d0.png)

## Site 2
![image](https://user-images.githubusercontent.com/1004649/77942876-4e201480-728a-11ea-99b5-952128faab1c.png)

**Comment by nicjansma** [comment]
Unfortunately I'm not sure there's anything actionable for us to dig into here right now.  Closing, but happy to re-open the discussion if there are examples we can dig into.
