### ISSUE TITLE
Boomerang beacon values are inconsistent

### ISSUE THREAD

**Issue by SeanWhipple** [akamai/boomerang#296]
I have some boomerang data that is being collected, however the frame rate data this coming back doesn't make sense to me.

My two main questions are 

1. **Why does the frame rate timeline data not match up**
2. **Why is the TTI as high as it is**

First I'll give the complete beacon I am seeing
```
c.e: "kb8jhepo"
c.f: 61
c.f.d: 524
c.f.m: 2
c.f.s: "kb8jhge3"
c.t.fps: "0*5*62"
c.tti: 2075
c.tti.m: "lt"
c.tti.vr: 948
if: ""
n: 1
nt_con_end: 1591744341954
nt_con_st: 1591744341954
nt_dec_size: 129958
nt_dns_end: 1591744341954
nt_dns_st: 1591744341954
nt_domcomp: 1591744343076
nt_domcontloaded_end: 1591744342895
nt_domcontloaded_st: 1591744342814
nt_domint: 1591744342577
nt_domloading: 1591744342159
nt_enc_size: 41324
nt_fet_st: 1591744341954
nt_first_paint: 1591744342325
nt_load_end: 1591744343120
nt_load_st: 1591744343082
nt_nav_st: 1591744341948
nt_nav_type: 1
nt_protocol: "h2"
nt_red_cnt: 0
nt_req_st: 1591744341964
nt_res_end: 1591744342373
nt_res_st: 1591744342144
nt_ssl_st: 1591744341954
nt_trn_size: 42860
nt_unload_end: 1591744342154
nt_unload_st: 1591744342154
pid: "a6ilbd4j"
pt.fcp: 377
pt.fp: 377
rt.si: "kd7mvv6mutl-NaN"
rt.sl: 0
rt.ss: undefined
ua.plt: "MacIntel"
ua.vnd: "Google Inc."
v: "1.0.0"
vis.st: "visible"
```

On the [doc](https://developer.akamai.com/tools/boomerang/docs/BOOMR.plugins.Continuity.html) the algorithm calculating TTI is summarized w/ 
```
Putting these two timers together, here's how we measure Visually Ready and Time to Interactive:

1. Determine the highest Visually Ready timestamp (VRTS):

  * Largest Contentful Paint (if available)
  * First Contentful Paint (if available)
  * First Paint (if available)
  * domContentLoadedEventEnd
  * Hero Images are loaded (if configured)
  * Framework Ready (if configured)

2. After VRTS, calculate Time to Interactive by finding the first period of 500ms where all of the following are true:

  * There were no Long Tasks
  * The FPS was always above 20 (if available)
  * Page Busy was less than 10% (if the above aren't available)
```

**Frame Rate**

The `c.f` equals 61 which according to the [docs](https://developer.akamai.com/tools/boomerang/docs/BOOMR.plugins.Continuity.html) is the average frame rate over the duration base.  However when I take the timeline data which is given in `c.t.fps` I get a compressed value of `"0*5*62"`, which when I decompress according to the algorithm I get `[6, 6, 6, 6, 6, 2]`, which clearly does not average out to 61.

The frame rate duration `c.f.d` is 524 ms which makes why I have that number of data points but I don't see how the average matches up with the timeline.

Bonus question:  can someone provide insight into when the frame rate starts and stops being measured?

**TTI**

The TTI is even more confusing IMO.  The value I'm getting from the beacon 2075 and the method used was `lt` (or LongTask).  However the other data points don't support that being the TTI value.  The time to visually ready is much lower at 948, there are is no long task data in the beacon so presumably this was not a factor in calculating TTI.  

The last thing left is frame rate which as mentioned above doesn't seem to grok for me.  None of the timeline points are ever over 20 fps which is what the documentation says it's looking for.  It's not clear to me when (or if ever) the frame rate met those requirements

**Comment by SeanWhipple** [comment]
I took a stab at trying to answer this myself

The array of `[6, 6, 6, 6, 6, 2]` is more like frames per 100 ms than fps.  The TTI is really calculated on this [block](https://github.com/akamai/boomerang/blob/master/plugins/continuity.js#L1656).
```
if (idleIntervals >= TIME_TO_INTERACTIVE_IDLE_INTERVALS) {
  tti = startTime + ((j - TIME_TO_INTERACTIVE_IDLE_INTERVALS) * COLLECTION_INTERVAL);

  // ensure we don't set TTI before TTVR
  tti = Math.max(tti, visuallyReady);
  break;
}
```

What it's really saying there is that the number of consecutive `idleIntervals` needs to be >= 5 (`TIME_TO_INTERACTIVE_IDLE_INTERVALS`).

In my case above we had no long task data and time to visually ready happened before tti so that left us with the frame rates per second.  As mentioned above I was interpreting those rates incorrectly

When it's using fps to determine if an interval was idle it using the following code [block](https://github.com/akamai/boomerang/blob/master/plugins/continuity.js#L1632)

```
if (data.fps && (!data.fps[j] || data.fps[j] < TIME_TO_INTERACTIVE_MIN_FPS_PER_INTERVAL)) {
  // No FPS or less than 20 FPS during this interval
  idleIntervals = 0;
  continue;
}
```

`TIME_TO_INTERACTIVE_MIN_FPS_PER_INTERVAL` is actually `2`, is calculated on this line `https://github.com/akamai/boomerang/blob/master/plugins/continuity.js#L1167`

So frame rate per second is the limiting factor in tti value.  The first 5 frame rate values measured were considered "good" for tti.  But the reason it's still so much higher than the ttvr is because the frame rate didn't start being measured till later.

The time when when frame rate started being measured is given by the beacon value `c.f.s` (a base36 encoded epoch time).  The time when anything being measured by boomerang is given by `c.e`.  If you take the difference of these two in by beacon example in the wiki, you get the tti value being returned by boomerang

**Comment by nicjansma** [comment]
Hi @SeanWhipple!

Thank you for sharing your question, and apologies for the delay in response.  Great debugging!

You're correct that the `c.t.fps` "FPS Timeline" data is split up by the `COLLECTION_INTERVAL`, which is every 100ms.  Each bucket represents frames seen during that 100ms.

The value of `[6, 6, 6, 6, 6, 2]` thus indicates mostly 6 frames each 100ms interval, which is the maximum you can get at 60hz (`100/(1000/60)=6`).  The last 100ms interval containing 2 frames might've been a "partial" interval that wasn't complete yet.  The `c.f.d` "FPS Duration" of `524` kind of confirms that -- there were 5 full 100ms intervals plus another partial one of 24ms.

> What it's really saying there is that the number of consecutive idleIntervals needs to be >= 5 (TIME_TO_INTERACTIVE_IDLE_INTERVALS).

Correct -- for our Time to Interactive calculation, there needs to be 5 intervals (so 500ms) where:

```
 *     * There were no Long Tasks
 *     * The FPS was always above 20 (if available)
 *     * Page Busy was less than 10% (if the above aren't available)
```

We then mark TTI as the beginning of that idle period.

`c.tti.m: "lt"` indicates this was a browser that _supports_ Long Tasks, but since there was no `c.lt` Long Task data, it's likely there were no Long Tasks during this load.  If Long Tasks are supported, we also measure Frame Rate, but we don't monitor "Page Busy" (idle polling).

Thus for this beacon, we look at Long Task data (there was none) and FPS for calculating TTI.

For this page load, it looks like the timeline is:

* First (+Contentful) Paint @ 377ms (`pt.fp` `pt.fcp`)
* Time To Visually Ready @ 948ms (`c.tti.vr`)
* Page Load @ 1,134ms (`nt_load_st-nt_nav_st`)
* Time to Interactive @ 2,075ms (`c.tti`)

And since Boomerang only reported 524ms of FPS data, Boomerang itself probably loaded after the Page Load event.  The first time FPS data was recorded, `c.f.s`, can be translated via `parseInt("kb8jhge3", 36) = 1591744344123`, or @ 2,175ms, after Page Load, and right around when we marked TTI.  Is Boomerang being loaded async via the suggested Loader Snippet?

In this case, looking for 5 "idle intervals" to calculate TTI might not be entirely accurate, since unfortunately we're looking "back in time" and don't have FPS data for the full page load, which happened as early as 1,134ms.  It's possible all of those periods after Page Load had full FPS, but since Boomerang wasn't there, we couldn't measure it.

It looks like Boomerang is basically reporting the time **it loaded** as TTI, since it doesn't have earlier data to report otherwise (no Long Tasks, and FPS starts when Boomerang loads).  I think this will mostly affect "fast" pages where Boomerang loads late in the page.

Was this a page that was a test site with minimal content, or just a really fast loading page?

There is a way to work around this issue for fast-loading pages, or where Boomerang loads late in the process (at-or-after `onload`), which is to use a Header Snippet to measure FPS from the time the page starts.  This would go directly in a `<script>` tag on each page.  Once Boomerang loads, it will take over this FPS information and incorporate it into its TTI measurements.

Check out the _Frame Rate_ header snippet here:
https://developer.akamai.com/tools/boomerang/docs/tutorial-header-snippets.html

That does leave us with deciding what we should do with TTI calculations in the scenario without a Header Snippet.  I don't think its necessarily accurate to have Boomerang just report the time it loaded, especially if it's being loaded async.  Without FPS data going back-in-time, we don't *really* know when our calculated TTI happened.  Maybe we should not send `c.tti` in that case, and note on the beacon that we loaded too late?

**Comment by SeanWhipple** [comment]
Sorry for the late reply and thank you for your response!  All of that makes perfect sense.

Regarding what to do on the case when Boomerang just isn't loaded fast enough to capture the "true" TTI I'm not sure what the right response is.  I think I like knowing that number if nothing else it gives good information on how long it's taking Boomerang to be loaded and ready to go.  But it might be worth marking the beacon with a flag that indicates that.

Not sure if it's appropriate to re-use the TTI method beacon value or if it's lightweight enough to add a new one that indicates this condition happened.

For my purposes we're okay with the current behavior as we're more worried about slow page loads where this is far less likely to be an issue.  But I do think knowing that Boomerang reported its first time as the TTI time (without having to go deep into the beacon metrics) would be valuable.  I'll close this ticket for now as the root cause of this was more an explanation of the existing behavior
