### ISSUE TITLE
AutoXHR Clicks

### ISSUE THREAD

**Issue by mzheng15** [akamai/boomerang#304]
In the AutoXHR documentation it says:

<img width="471" alt="Screen Shot 2020-08-03 at 2 05 31 PM" src="https://user-images.githubusercontent.com/22859161/89227437-874af700-d592-11ea-8a3b-6543003c1730.png">

Does this mean that I cannot have the History plugin enabled? Or is it talking about other plugins and if so what are some examples?
Also, do I need the Clicks plugin in order to XHR to track clicks or are they seperate?

Thanks

**Comment by nicjansma** [comment]
In `auto-xhr.js`, we explicitly disable generic `click` if the SPA plugins are enabled, since those plugins are more interested in tracking route changes than just clicks.  Relevant code is here: https://github.com/akamai/boomerang/blob/master/plugins/auto-xhr.js#L1587-L1592

That applies to the History plugin (and any of the other legacy Angular/Backbone/etc plugins).

The actual `clicks.js` plugin is separate and unrelated to the `auto-xhr.js` tracking.

**Comment by mc-chaos** [comment]
@mzheng15 : Could this issue closed?
Regards, Sascha
