### ISSUE TITLE
What is the use of the last_location function in spa plugin

### ISSUE THREAD

**Issue by vkbandi** [akamai/boomerang#349]
I was going through the spa plugin code and found the last_location function is not called from anywhere else in the codebase, is this code safe to remove, the actual code inside the function also doesn't appear to be doing anything as the `lastLocationChange` variables that is being updated there is not used anywhere else, am I missing anything, or is this piece of code safe to remove ?

https://github.com/akamai/boomerang/blob/724474abd9d10359eaf4a30d5c67fb215c738217/plugins/spa.js#L495

**Comment by ceckoslab** [comment]
Hello @vkbandi 

It looks like function was used in older version of Boomerang.

I think that we left this public setter because we didn't want to cause JavaScript errors for the people who were already using it.

I will check with the team and discuss if we need to add better documentation and perhaps a deprecation log message in the Browser's console when this method is being called.

**Comment by vkbandi** [comment]
Is it ok, if we close this issue ?
